

export const APP_CONFIG = {
    APPWRITE:{
        KEY:process.env.NEXT_APPWRITE_KEY!,
        ENDPOINT:process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
        PROJECT_ID:process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
        DATABASE_ID:process.env.NEXT_PUBLIC_APPWRITE_DATABASE!,
        SHOP_ID:process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID!,
        CART_LISTING_ID:process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CAR_LISTING_ID!
    }
}